### ISSUE TITLE
Property type of DateTime on POCO 

### ISSUE THREAD

**Issue by carlblanchard** [giometrix/TableStorage.Abstractions.POCO#12]
Your library is very good, I have been trialling a couple of AzureTable to Poco's libraries and I like the look of yours very much so. 

However, I have encountered a little problem when a properties data type is DateTime the following conversion error is produced. 

Object of type 'System.String' cannot be converted to type 'System.DateTime'.

Is this something you can address? I am currently changing the property to a string as a workaround but unfortunately, that is breaking the data binding in razor pages and a DateTime picker is no longer setting a default value due to the string datatype. 
Hence the importance that the library should set the correct datatype. 

Look forward to your reply. 

Regards Carl.

**Comment by giometrix** [comment]
Sure , I'll try to look into it this week.

Can you tell me the format of the string so I can test appropriately?

**Comment by carlblanchard** [comment]
Cool, try with  01/11/2021 also 2021-11-14

**Comment by giometrix** [comment]
OK, let me know what you think of this.  I'm going to let it sit in beta for a few days in case we can think of a nicer way to do this.

I also opted to only overload `SimpleKeysConverter` and `CalculatedKeysConverter` as to not overload the easier to use APIs as I don't think this feature will be used too often.  This means that instantiation is slightly less straight forward, but I think it's still reasonable.  Also, you're probably not instantiating `PocoTableStore`s all over the place, so I don't think it will be too bad.

First we need to declare the custom converters, here is an example:

```csharp
var propertyConverters = new PropertyConverters<EmployeeWithHireDate>
	{
		[nameof(EmployeeWithHireDate.HireDate)] = new PropertyConverter<EmployeeWithHireDate>(
			e=>new EntityProperty(e.HireDate.ToString("yyyy-M-d")),
					(e,p)=>e.HireDate = DateTime.Parse(p.StringValue))
	};
```

Notice it is a dictionary, so you can have as many converters per class as you need.  Converting partition/row keys will not work via this approach.

Next we define a key converter.  Normally you don't need to do this for the basic use cases because it's done for you under the hood, but as I said, I thought it would be best to keep this new functionality out of the normal constructors as they are already getting a little cumbersome.

Here is an example:

```csharp

var simpleKeyConverter = new SimpleKeysConverter<EmployeeWithHireDate, int, int>(e => e.CompanyId, e => e.Id,
	new JsonSerializerSettings(), propertyConverters, default);
	
var tableStore = new PocoTableStore<EmployeeWithHireDate, int, int>("TestEmployee", "UseDevelopmentStorage=true",
				simpleKeyConverter);
```

From here on out you use the library as you did in the past.



The beta is on nuget : https://www.nuget.org/packages/TableStorage.Abstractions.POCO/3.1.0-beta

Please click the "beta" checkbox in Visual Studio/Rider, as they hide beta releases.

Let me know your thoughts!

**Comment by carlblanchard** [comment]
Thank you for the really quick turnaround. I've implemented the code as you advised and it's working great. 
I guess this is a nice way to handle any future issues also. Just add to the property converter and off you go. 
Awesome work my friend your library works very well.  I must say I am really impressed how simple it makes working with azure storage tables and far more logical to use POCO objects rather than KeyValue pairs.
